Repository googleapis/python-bigquery-magics, pull requests merged in 2024-04, with the labels that each got.

#7 chore: grant api-bigquery and api-bigquery-dataframe teams write access to repo
  .github/sync-repo-settings.yaml
Labels: api: bigquery

#22 docs: reset the changelog for the new bigquery-magics package
  CHANGELOG.md
Labels: api: bigquery, size: xl

#19 chore: update required checks
  .github/sync-repo-settings.yaml
Labels: api: bigquery, size: s

#9 chore: add bigquery-magics samples
  bigquery_magics/bigquery.py
  docs/index.rst
  docs/magics.rst
  samples/snippets/__init__.py
  samples/snippets/_helpers.py
  samples/snippets/conftest.py
  samples/snippets/mypy.ini
  samples/snippets/noxfile.py
  samples/snippets/query.py
  samples/snippets/query_params_scalars.py
  samples/snippets/query_params_scalars_test.py
  samples/snippets/query_test.py
  samples/snippets/requirements-test.txt
  samples/snippets/requirements.txt
Labels: samples, api: bigquery, size: l

#24 docs: clean up docs and let the nox pass
  README.rst
  docs/bigquery/legacy_proto_types.rst
  docs/index.rst
  docs/magics.rst
  docs/usage/client.rst
  docs/usage/datasets.rst
  docs/usage/encryption.rst
  docs/usage/index.rst
  docs/usage/jobs.rst
  docs/usage/pandas.rst
  docs/usage/queries.rst
  docs/usage/tables.rst
Labels: api: bigquery, size: l

#25 chore: add samples tests as required checks
  .github/sync-repo-settings.yaml
Labels: samples, api: bigquery, size: s
